// agentsData.js
export const agentsData = [
    {
      title: "CustomerFinderBot",
      subtitle: "Personal Assistant",
      description: "Discover your customers in seconds with social media AI.",
      percentage: "7.20%",
      bgColor: "bg-primaryBlue",
      textColor: "text-white",
      linkColor: "bg-white text-primaryBlue",
    },
    {
      title: "SEObotAI",
      subtitle: "Digital Workers",
      description: "AI-powered SEO automation platform.",
      percentage: "14.20%",
      bgColor: "bg-gray-200",
      textColor: "text-primaryBlue",
      linkColor: "bg-primaryBlue text-white",
    },
    {
      title: "FocusAI",
      subtitle: "Strategy",
      description: "Get focused life planning, roadmap or guide.",
      percentage: "11.20%",
      bgColor: "bg-white",
      textColor: "text-primaryBlue",
      linkColor: "bg-primaryBlue text-white",
    },
    {
      title: "Fixed IncomeAI",
      subtitle: "Fixed Income",
      description: "Get multiple benefits, and lump sum options.",
      percentage: "8.20%",
      bgColor: "bg-blue-100",
      textColor: "text-primaryBlue",
      linkColor: "bg-primaryBlue text-white",
    },
    // Add 6 more agents
    {
      title: "MarketPredictAI",
      subtitle: "Analytics",
      description: "Predict market trends with advanced AI algorithms.",
      percentage: "12.50%",
      bgColor: "bg-green-100",
      textColor: "text-primaryBlue",
      linkColor: "bg-primaryBlue text-white",
    },
    {
      title: "SalesBoostAI",
      subtitle: "Sales",
      description: "Enhance your sales strategies with AI insights.",
      percentage: "9.80%",
      bgColor: "bg-yellow-100",
      textColor: "text-primaryBlue",
      linkColor: "bg-primaryBlue text-white",
    },
    {
      title: "ContentGenAI",
      subtitle: "Content Creation",
      description: "Generate high-quality content effortlessly.",
      percentage: "10.30%",
      bgColor: "bg-purple-100",
      textColor: "text-primaryBlue",
      linkColor: "bg-primaryBlue text-white",
    },
    {
      title: "ChatSupportAI",
      subtitle: "Customer Support",
      description: "Provide 24/7 customer support with AI chatbots.",
      percentage: "13.10%",
      bgColor: "bg-pink-100",
      textColor: "text-primaryBlue",
      linkColor: "bg-primaryBlue text-white",
    },
    {
      title: "InventoryAI",
      subtitle: "Inventory Management",
      description: "Optimize your inventory with AI-driven insights.",
      percentage: "6.75%",
      bgColor: "bg-indigo-100",
      textColor: "text-primaryBlue",
      linkColor: "bg-primaryBlue text-white",
    },
    {
      title: "HRAssistAI",
      subtitle: "Human Resources",
      description: "Streamline your HR processes with AI assistance.",
      percentage: "15.00%",
      bgColor: "bg-teal-100",
      textColor: "text-primaryBlue",
      linkColor: "bg-primaryBlue text-white",
    },
  ];
  